version: "0.5"

# Global environment is imported from project .env: $PROJECT/.env
# in container, it's /home/user/tangram/.env
#
# environment:
# - "RS1090_SOURCE_BASE_URL=http://host.containers.internal:8080"
# - "REDIS_URL=redis://redis:6379"
# - "RS1090_SOURCE_BASE_URL=http://jet1090:8080"
log_location: /tmp/pc.log
log_level: debug

processes:
  web:
    working_dir: /home/user/tangram/web
    command: just run-web
    availability:
      restart: "always"

  service:
    environment:
    command: just run-service
    working_dir: /home/user/tangram/service
    availability:
      restart: "always"

  plugins/streaming:
    environment:
      - "UV_PROJECT_ENVIRONMENT=/home/user/.local/share/venvs/tangram"
    working_dir: /home/user/tangram/service
    command: env && pwd && uv run -- python -m tangram.plugins.streaming
    availability:
      restart: "always"

  plugins/history:
    environment:
      - "UV_PROJECT_ENVIRONMENT=/home/user/.local/share/venvs/tangram"
    working_dir: /home/user/tangram/service
    command: env && pwd && uv run -- python -m tangram.plugins.history
    availability:
      restart: "always"
