services:
  redis:
    image: "redis:7.4"
    container_name: tg-redis
    ports:
      - 6379:6379

  service:
    env_file: ./.env
    build:
      context: .
      dockerfile: ./container/srv.Dockerfile
      args:
        HTTPS_PROXY:
        HTTP_PROXY:
    container_name: tg-svc
    dns:
      - "1.1.1.1"
    ports:
      - "18000:18000"
    volumes:
      - .:/home/user/tangram
    # command: bash -c "env"

  web:
    image: node:20-slim
    env_file: .env
    container_name: tg-web
    user: node
    volumes:
      - ./web:/web
    ports:
      - 2024:2024
    working_dir: /web
    command: bash -c "npm install -v && npm install -d -v && npx vite --debug --port 2024 --host 0.0.0.0"
  # web:
  #   # image: tangram/web
  #   env_file: .env
  #   build:
  #     context: .
  #     dockerfile: container/web.Dockerfile
  #     args:
  #       HTTPS_PROXY:
  #       HTTP_PROXY:
  #   container_name: tg-web
  #   volumes:
  #     - ./web:/web
  #   working_dir: /web
