[tool.poetry]
name = "turbulences"
version = "0.1.0"
description = ""
authors = ["Michel Khalaf <khalafmichel98@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
turb = 'turbulences.__main__:main'

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
traffic = "^2.6.6"
appdirs = "^1.4.4"
Flask = "^2.0.2"
Flask-Assets = "^2.0"
atmlab = {git = "ssh://git@github.com/xoolive/atmlab.git"}
waitress = "^2.0.0"
click = "^8.0.3"
Flask-PyMongo = "^2.3.0"
Flask-WTF = "^1.0.0"
Flask-Cors = "^3.0.10"
Paste = "^3.5.0"

[tool.poetry.dev-dependencies]
mypy = "^0.920"
black = "^21.12b0"
isort = "^5.10.1"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 80
target_version = ['py37', 'py38', 'py39']
include = '\.pyi?$'
exclude = '''
/(
    __pycache__
  | \.git
  | \.mypy_cache
  | \.ipynb_checkpoints
  | build
  | dist
)/
'''

[tool.isort]
line_length = 80
profile = "black"
known_first_party = ["numpy", "pandas", "pyproj", "shapely"]

[tool.mypy]
python_version = 3.7
platform = "posix"

color_output = true
pretty = true
show_column_numbers = true
strict = true

# probably redundant, but useful when switching strict to false
check_untyped_defs = true
ignore_missing_imports = true
warn_no_return = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
