[tool.poetry]
name = "turbulence"
version = "0.1.0"
description = ""
authors = ["Michel Khalaf <khalafmichel98@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
turbulence = 'turbulence.__main__:main'
decoder = 'turbulence.scripts.decoder:main'
aggregator = 'turbulence.scripts.aggregator:main'

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
traffic = "^2.8.0"
# traffic = { path = "../traffic/dist/traffic-2.8.0.tar.gz" }
appdirs = "^1.4.4"
Flask = "^2.0.2"
Flask-Assets = "^2.0"
# atmlab = {git = "ssh://git@github.com/xoolive/atmlab.git"}
# atmlab = { path = "../atmlab/dist/atmlab-0.1.0.tar.gz" }
atmlab = ">=0.1.0"
waitress = "^2.0.0"
click = "^8.0.3"
Flask-WTF = "^1.0.0"
Flask-Cors = "^3.0.10"
pymongo = ">=3.12,<4"
Flask-PyMongo = "^2.3.0"

[tool.poetry.dev-dependencies]
mypy = ">=0.950"
black = ">=21.6"
isort = "^5.10.1"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 80
target_version = ['py37', 'py38', 'py39']
include = '\.pyi?$'
exclude = '''
/(
    __pycache__
  | \.git
  | \.mypy_cache
  | \.ipynb_checkpoints
  | build
  | dist
)/
'''

[tool.isort]
line_length = 80
profile = "black"
known_first_party = ["numpy", "pandas", "pyproj", "shapely"]

[tool.mypy]
python_version = 3.7
platform = "posix"

color_output = true
pretty = true
show_column_numbers = true
strict = true

# probably redundant, but useful when switching strict to false
check_untyped_defs = true
ignore_missing_imports = true
warn_no_return = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
